package demo.turbo.greendaodemo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PERSON_TABLE".
*/
public class PersonTableDao extends AbstractDao<PersonTable, Long> {

    public static final String TABLENAME = "PERSON_TABLE";

    /**
     * Properties of entity PersonTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property _id = new Property(0, long.class, "_id", true, "_ID");
        public final static Property _name = new Property(1, String.class, "_name", false, "_NAME");
        public final static Property _address = new Property(2, String.class, "_address", false, "_ADDRESS");
    };


    public PersonTableDao(DaoConfig config) {
        super(config);
    }
    
    public PersonTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PERSON_TABLE\" (" + //
                "\"_ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: _id
                "\"_NAME\" TEXT NOT NULL ," + // 1: _name
                "\"_ADDRESS\" TEXT NOT NULL );"); // 2: _address
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PERSON_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PersonTable entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.get_id());
        stmt.bindString(2, entity.get_name());
        stmt.bindString(3, entity.get_address());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PersonTable entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.get_id());
        stmt.bindString(2, entity.get_name());
        stmt.bindString(3, entity.get_address());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public PersonTable readEntity(Cursor cursor, int offset) {
        PersonTable entity = new PersonTable( //
            cursor.getLong(offset + 0), // _id
            cursor.getString(offset + 1), // _name
            cursor.getString(offset + 2) // _address
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PersonTable entity, int offset) {
        entity.set_id(cursor.getLong(offset + 0));
        entity.set_name(cursor.getString(offset + 1));
        entity.set_address(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PersonTable entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PersonTable entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
