package demo.turbo.greendaodemo.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON_TABLE".
 */
@Entity
public class PersonTable {

    @Id
    private long _id;

    @NotNull
    private String _name;

    @NotNull
    private String _address;

    @Generated
    public PersonTable() {
    }

    public PersonTable(long _id) {
        this._id = _id;
    }

    @Generated
    public PersonTable(long _id, String _name, String _address) {
        this._id = _id;
        this._name = _name;
        this._address = _address;
    }

    public long get_id() {
        return _id;
    }

    public void set_id(long _id) {
        this._id = _id;
    }

    @NotNull
    public String get_name() {
        return _name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void set_name(@NotNull String _name) {
        this._name = _name;
    }

    @NotNull
    public String get_address() {
        return _address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void set_address(@NotNull String _address) {
        this._address = _address;
    }

}
