package demo.turbo.greendaodemo.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "POINT".
 */
@Entity
public class Point {

    @Id
    private Long id;
    private double xPos;
    private double yPos;

    @Generated
    public Point() {
    }

    public Point(Long id) {
        this.id = id;
    }

    @Generated
    public Point(Long id, double xPos, double yPos) {
        this.id = id;
        this.xPos = xPos;
        this.yPos = yPos;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getXPos() {
        return xPos;
    }

    public void setXPos(double xPos) {
        this.xPos = xPos;
    }

    public double getYPos() {
        return yPos;
    }

    public void setYPos(double yPos) {
        this.yPos = yPos;
    }

}
