package demo.turbo.greendaodemo.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TABLE1".
 */
@Entity
public class table1 {

    @Id
    private int _id;

    @NotNull
    private String name;

    @NotNull
    private String address;

    @Generated
    public table1() {
    }

    public table1(int _id) {
        this._id = _id;
    }

    @Generated
    public table1(int _id, String name, String address) {
        this._id = _id;
        this.name = name;
        this.address = address;
    }

    public int get_id() {
        return _id;
    }

    public void set_id(int _id) {
        this._id = _id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(@NotNull String address) {
        this.address = address;
    }

}
